import os
from jira import JIRA

def create_jira_ticket(classification: dict, cookbook: str) -> str:
    """
    Creates a Jira ticket for critical incidents.
    Uses real Jira API if credentials are provided, otherwise mocks it.
    """
    jira_url = os.getenv("JIRA_SERVER_URL")
    jira_user = os.getenv("JIRA_USER_EMAIL")
    jira_token = os.getenv("JIRA_API_TOKEN")
    project_key = os.getenv("JIRA_PROJECT_KEY", "OPS")

    severity = classification.get("severity", "unknown").upper()
    root_cause = classification.get("root_cause", "Unknown issue")
    confidence = classification.get("confidence", "N/A")

    summary = f"[{severity}] Incident: {root_cause}"
    description = (
        f"*Auto-generated by Multi-Agent Incident Analyzer*\n\n"
        f"h2. Incident Classification\n"
        f"||Field||Value||\n"
        f"|Severity|{severity}|\n"
        f"|Root Cause|{root_cause}|\n"
        f"|Confidence|{confidence}|\n\n"
        f"h2. Recovery Cookbook\n"
        f"{cookbook}\n"
    )

    if all([jira_url, jira_user, jira_token]):
        try:
            jira = JIRA(
                server=jira_url,
                basic_auth=(jira_user, jira_token)
            )

            # Auto-detect available issue types for this project
            project_meta = jira.project(project_key)
            issue_types = jira.issue_types_for_project(project_key)
            available_types = [it.name for it in issue_types]
            print(f"📋 Available issue types for {project_key}: {available_types}")

            # Pick the best issue type
            preferred = ["Task", "Bug", "Story", "Incident"]
            chosen_type = None
            for pref in preferred:
                if pref in available_types:
                    chosen_type = pref
                    break
            if not chosen_type and available_types:
                chosen_type = available_types[0]  # Use whatever is available

            if not chosen_type:
                return f"Jira Error: No issue types found for project {project_key}"

            print(f"✅ Using issue type: {chosen_type}")

            new_issue = jira.create_issue(
                project=project_key,
                summary=summary,
                description=description,
                issuetype={"name": chosen_type},
            )

            ticket_id = str(new_issue.key)
            ticket_url = f"{jira_url}/browse/{ticket_id}"
            print(f"✅ Jira Ticket Created: {ticket_id} → {ticket_url}")
            return f"{ticket_id} ({ticket_url})"

        except Exception as e:
            print(f"❌ Jira API Error: {e}")
            return f"Jira Error: {e}"
    else:
        # Mock mode
        mock_ticket_id = "OPS-MOCK-1001"
        print(f"⚠️  Jira credentials not set. Mocked ticket: {mock_ticket_id}")
        print(f"   Summary: {summary}")
        return mock_ticket_id
